services:
  - type: web
    name: c-code-optimizer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y clang
      pip install -r requirements.txt
      mkdir -p uploads
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /