services:
  - type: web
    name: flask-app
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production